make_diff_pair_ports db_rx_data0_P db_rx_data0_N
make_diff_pair_ports db_rx_data1_P db_rx_data1_N
make_diff_pair_ports db_rx_data10_P db_rx_data10_N
make_diff_pair_ports db_rx_data2_P db_rx_data2_N
make_diff_pair_ports db_rx_data3_P db_rx_data3_N
make_diff_pair_ports db_rx_data4_P db_rx_data4_N
make_diff_pair_ports db_rx_data5_P db_rx_data5_N
make_diff_pair_ports db_rx_data6_P db_rx_data6_N
make_diff_pair_ports db_rx_data7_P db_rx_data7_N
make_diff_pair_ports db_rx_data8_P db_rx_data8_N
make_diff_pair_ports db_rx_data9_P db_rx_data9_N
make_diff_pair_ports db_tx_data0_P db_tx_data0_N
make_diff_pair_ports db_tx_data1_P db_tx_data1_N
make_diff_pair_ports db_tx_data10_P db_tx_data10_N
make_diff_pair_ports db_tx_data2_P db_tx_data2_N
make_diff_pair_ports db_tx_data3_P db_tx_data3_N
make_diff_pair_ports db_tx_data4_P db_tx_data4_N
make_diff_pair_ports db_tx_data5_P db_tx_data5_N
make_diff_pair_ports db_tx_data6_P db_tx_data6_N
make_diff_pair_ports db_tx_data7_P db_tx_data7_N
make_diff_pair_ports db_tx_data8_P db_tx_data8_N
make_diff_pair_ports db_tx_data9_P db_tx_data9_N
set_property -dict { PACKAGE_PIN AD15 IOSTANDARD LVCMOS33 PULLTYPE PULLDOWN } [ get_ports synce_clk_125mhz ]
set_property -dict { PACKAGE_PIN AB15 IOSTANDARD LVCMOS33 PULLTYPE PULLDOWN } [ get_ports eth_ptp ]
set_property -dict { PACKAGE_PIN AC14 IOSTANDARD LVCMOS33 PULLTYPE PULLDOWN } [ get_ports pl_clk1 ]
set_property -dict { PACKAGE_PIN AG14 IOSTANDARD LVCMOS33 } [ get_ports sys_pl_gpio0 ]
set_property -dict { PACKAGE_PIN AH14 IOSTANDARD LVCMOS33 } [ get_ports sys_pl_gpio1 ]
set_property -dict { PACKAGE_PIN AG13 IOSTANDARD LVCMOS33 } [ get_ports sys_pl_gpio2 ]
set_property -dict { PACKAGE_PIN AH13 IOSTANDARD LVCMOS33 } [ get_ports sys_pl_gpio3 ]
set_property -dict { PACKAGE_PIN AE13 IOSTANDARD LVCMOS33 } [ get_ports sys_pl_gpio4 ]
set_property -dict { PACKAGE_PIN AF13 IOSTANDARD LVCMOS33 } [ get_ports sys_pl_gpio5 ]
set_property -dict { PACKAGE_PIN AE15 IOSTANDARD LVCMOS33 } [ get_ports sys_pl_gpio6 ]
set_property -dict { PACKAGE_PIN AE14 IOSTANDARD LVCMOS33 } [ get_ports sys_pl_gpio7 ]
set_property -dict { PACKAGE_PIN A10 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio0 ]
set_property -dict { PACKAGE_PIN C12 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio1 ]
set_property -dict { PACKAGE_PIN E10 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio10 ]
set_property -dict { PACKAGE_PIN D11 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio11 ]
set_property -dict { PACKAGE_PIN F10 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio12 ]
set_property -dict { PACKAGE_PIN C11 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio13 ]
set_property -dict { PACKAGE_PIN D12 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio14 ]
set_property -dict { PACKAGE_PIN D10 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio15 ]
set_property -dict { PACKAGE_PIN F12 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio2 ]
set_property -dict { PACKAGE_PIN A12 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio3 ]
set_property -dict { PACKAGE_PIN E12 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio4 ]
set_property -dict { PACKAGE_PIN B11 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio5 ]
set_property -dict { PACKAGE_PIN F11 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio6 ]
set_property -dict { PACKAGE_PIN A11 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio7 ]
set_property -dict { PACKAGE_PIN G11 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio8 ]
set_property -dict { PACKAGE_PIN B10 IOSTANDARD LVCMOS33 } [ get_ports ext_gpio9 ]
set_property -dict { PACKAGE_PIN G15 IOSTANDARD LVCMOS33 PULLTYPE PULLDOWN } [ get_ports mclk_fdec ]
set_property -dict { PACKAGE_PIN F15 IOSTANDARD LVCMOS33 PULLTYPE PULLDOWN } [ get_ports mclk_finc ]
set_property -dict { PACKAGE_PIN F13 IOSTANDARD LVCMOS33 PULLTYPE PULLUP } [ get_ports mclk_sync_b ]
set_property -dict { PACKAGE_PIN E15 IOSTANDARD LVCMOS33 PULLTYPE PULLDOWN } [ get_ports pl_clk2 ]
set_property -dict { PACKAGE_PIN A15 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 16 } [ get_ports pl_led_rx_b ]
set_property -dict { PACKAGE_PIN B15 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 12 } [ get_ports pl_led_rx_g ]
set_property -dict { PACKAGE_PIN A14 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8 } [ get_ports pl_led_rx_r ]
set_property -dict { PACKAGE_PIN B14 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 16 } [ get_ports pl_led_tx_b ]
set_property -dict { PACKAGE_PIN A13 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 12 } [ get_ports pl_led_tx_g ]
set_property -dict { PACKAGE_PIN B13 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8 } [ get_ports pl_led_tx_r ]
set_property -dict { PACKAGE_PIN E14 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8 } [ get_ports pwren_1p8v_adc ]
set_property -dict { PACKAGE_PIN E13 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8 } [ get_ports pwren_1p8v_adc_d ]
set_property -dict { PACKAGE_PIN C13 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8 } [ get_ports pwren_1p8v_dac ]
set_property -dict { PACKAGE_PIN C14 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8 } [ get_ports pwren_1p8v_dac_d ]
set_property -dict { PACKAGE_PIN D14 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8 } [ get_ports pwren_3p3v_adda ]
set_property -dict { PACKAGE_PIN AG11 IOSTANDARD LVCMOS33 } [ get_ports adc_tmp_alert ]
set_property -dict { PACKAGE_PIN AG10 IOSTANDARD LVCMOS33 } [ get_ports adc_tmp_scl ]
set_property -dict { PACKAGE_PIN AH11 IOSTANDARD LVCMOS33 } [ get_ports adc_tmp_sda ]
set_property -dict { PACKAGE_PIN AD12 IOSTANDARD LVCMOS33 } [ get_ports atsha_scl ]
set_property -dict { PACKAGE_PIN AD11 IOSTANDARD LVCMOS33 } [ get_ports atsha_sda ]
set_property -dict { PACKAGE_PIN AH10 IOSTANDARD LVCMOS33 } [ get_ports clken_pps ]
set_property -dict { PACKAGE_PIN AF11 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8 } [ get_ports pl_led_pps ]
set_property -dict { PACKAGE_PIN AF10 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8 } [ get_ports pl_led_ref ]
set_property -dict { PACKAGE_PIN AE12 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8 } [ get_ports pwren_1p8v_rfclk ]
set_property -dict { PACKAGE_PIN AB8 IOSTANDARD LVCMOS18 PULLTYPE PULLDOWN } [ get_ports pps_in_fpga ]
set_property -dict { PACKAGE_PIN AE9 IOSTANDARD LVCMOS18} [ get_ports adc_cs_b ]
set_property -dict { PACKAGE_PIN AB7 IOSTANDARD LVCMOS18} [ get_ports adc_fda ]
set_property -dict { PACKAGE_PIN AH6 IOSTANDARD LVCMOS18} [ get_ports adc_fdb ]
set_property -dict { PACKAGE_PIN AB4 IOSTANDARD LVCMOS18} [ get_ports adc_oe_b ]
set_property -dict { PACKAGE_PIN AB3 IOSTANDARD LVCMOS18} [ get_ports adc_pdwn ]
set_property -dict { PACKAGE_PIN AE8 IOSTANDARD LVCMOS18} [ get_ports adc_sclk ]
set_property -dict { PACKAGE_PIN AE7 IOSTANDARD LVCMOS18} [ get_ports adc_sdio ]
set_property -dict { PACKAGE_PIN AE4 IOSTANDARD LVCMOS18} [ get_ports adc_sync ]
set_property -dict { PACKAGE_PIN AB5 IOSTANDARD LVCMOS18} [ get_ports rf_clk_m0 ]
set_property -dict { PACKAGE_PIN AB6 IOSTANDARD LVCMOS18} [ get_ports rf_clk_m1 ]
set_property -dict { PACKAGE_PIN AH9 IOSTANDARD LVCMOS18} [ get_ports rf_clk_m2 ]
set_property -dict { PACKAGE_PIN AG9 IOSTANDARD LVCMOS18} [ get_ports rf_clk_m3 ]
set_property -dict { PACKAGE_PIN AD9 IOSTANDARD LVCMOS18} [ get_ports rf_clk_m4 ]
set_property -dict { PACKAGE_PIN AC9 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8 } [ get_ports rf_clk_reset_b ]
set_property -dict { PACKAGE_PIN AC7 IOSTANDARD LVCMOS18} [ get_ports rf_clk_spi_clk ]
set_property -dict { PACKAGE_PIN AC6 IOSTANDARD LVCMOS18} [ get_ports rf_clk_spi_cs_b ]
set_property -dict { PACKAGE_PIN AD7 IOSTANDARD LVCMOS18} [ get_ports rf_clk_spi_di ]
set_property -dict { PACKAGE_PIN AC8 IOSTANDARD LVCMOS18} [ get_ports rf_clk_spi_do ]
set_property -dict { PACKAGE_PIN AG8 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d0_N ]
set_property -dict { PACKAGE_PIN AF8 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d0_P ]
set_property -dict { PACKAGE_PIN AF5 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d1_N ]
set_property -dict { PACKAGE_PIN AE5 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d1_P ]
set_property -dict { PACKAGE_PIN AH4 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d2_N ]
set_property -dict { PACKAGE_PIN AG4 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d2_P ]
set_property -dict { PACKAGE_PIN AF3 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d3_N ]
set_property -dict { PACKAGE_PIN AE3 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d3_P ]
set_property -dict { PACKAGE_PIN AH3 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d4_N ]
set_property -dict { PACKAGE_PIN AG3 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d4_P ]
set_property -dict { PACKAGE_PIN AH1 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d5_N ]
set_property -dict { PACKAGE_PIN AH2 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d5_P ]
set_property -dict { PACKAGE_PIN AG1 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d6_N ]
set_property -dict { PACKAGE_PIN AF1 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d6_P ]
set_property -dict { PACKAGE_PIN AF2 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d7_N ]
set_property -dict { PACKAGE_PIN AE2 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d7_P ]
set_property -dict { PACKAGE_PIN AD1 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d8_N ]
set_property -dict { PACKAGE_PIN AD2 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d8_P ]
set_property -dict { PACKAGE_PIN AC1 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d9_N ]
set_property -dict { PACKAGE_PIN AB1 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d9_P ]
set_property -dict { PACKAGE_PIN AC2 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d10_N ]
set_property -dict { PACKAGE_PIN AB2 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d10_P ]
set_property -dict { PACKAGE_PIN AG5 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d11_N ]
set_property -dict { PACKAGE_PIN AG6 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d11_P ]
set_property -dict { PACKAGE_PIN AH7 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d12_N ]
set_property -dict { PACKAGE_PIN AH8 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d12_P ]
set_property -dict { PACKAGE_PIN AF6 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d13_N ]
set_property -dict { PACKAGE_PIN AF7 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_d13_P ]
set_property -dict { PACKAGE_PIN AD4 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_dco_N ]
set_property -dict { PACKAGE_PIN AD5 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_dco_P ]
set_property -dict { PACKAGE_PIN AC3 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_or_N ]
set_property -dict { PACKAGE_PIN AC4 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports adc_or_P ]
set_property -dict { PACKAGE_PIN H2 IOSTANDARD LVCMOS18 } [ get_ports db_rx_data11 ]
set_property -dict { PACKAGE_PIN W9 IOSTANDARD LVCMOS18 } [ get_ports db_rx_data12 ]
set_property -dict { PACKAGE_PIN P9 IOSTANDARD LVCMOS18 } [ get_ports db_tx_data11 ]
set_property -dict { PACKAGE_PIN K5 IOSTANDARD LVCMOS18 } [ get_ports db_tx_data12 ]
set_property -dict { PACKAGE_PIN Y8 IOSTANDARD LVDS } [ get_ports db_rx_data0_N ]
set_property -dict { PACKAGE_PIN W8 IOSTANDARD LVDS } [ get_ports db_rx_data0_P ]
set_property -dict { PACKAGE_PIN V8 IOSTANDARD LVDS } [ get_ports db_rx_data1_N ]
set_property -dict { PACKAGE_PIN U8 IOSTANDARD LVDS } [ get_ports db_rx_data1_P ]
set_property -dict { PACKAGE_PIN T7 IOSTANDARD LVDS } [ get_ports db_rx_data10_N ]
set_property -dict { PACKAGE_PIN R7 IOSTANDARD LVDS } [ get_ports db_rx_data10_P ]
set_property -dict { PACKAGE_PIN J2 IOSTANDARD LVDS } [ get_ports db_rx_data2_N ]
set_property -dict { PACKAGE_PIN K2 IOSTANDARD LVDS } [ get_ports db_rx_data2_P ]
set_property -dict { PACKAGE_PIN K3 IOSTANDARD LVDS } [ get_ports db_rx_data3_N ]
set_property -dict { PACKAGE_PIN K4 IOSTANDARD LVDS } [ get_ports db_rx_data3_P ]
set_property -dict { PACKAGE_PIN H1 IOSTANDARD LVDS } [ get_ports db_rx_data4_N ]
set_property -dict { PACKAGE_PIN J1 IOSTANDARD LVDS } [ get_ports db_rx_data4_P ]
set_property -dict { PACKAGE_PIN V9 IOSTANDARD LVDS } [ get_ports db_rx_data5_N ]
set_property -dict { PACKAGE_PIN U9 IOSTANDARD LVDS } [ get_ports db_rx_data5_P ]
set_property -dict { PACKAGE_PIN T6 IOSTANDARD LVDS } [ get_ports db_rx_data6_N ]
set_property -dict { PACKAGE_PIN R6 IOSTANDARD LVDS } [ get_ports db_rx_data6_P ]
set_property -dict { PACKAGE_PIN K1 IOSTANDARD LVDS } [ get_ports db_rx_data7_N ]
set_property -dict { PACKAGE_PIN L1 IOSTANDARD LVDS } [ get_ports db_rx_data7_P ]
set_property -dict { PACKAGE_PIN L2 IOSTANDARD LVDS } [ get_ports db_rx_data8_N ]
set_property -dict { PACKAGE_PIN L3 IOSTANDARD LVDS } [ get_ports db_rx_data8_P ]
set_property -dict { PACKAGE_PIN T8 IOSTANDARD LVDS } [ get_ports db_rx_data9_N ]
set_property -dict { PACKAGE_PIN R8 IOSTANDARD LVDS } [ get_ports db_rx_data9_P ]
set_property -dict { PACKAGE_PIN H8 IOSTANDARD LVDS } [ get_ports db_tx_data0_N ]
set_property -dict { PACKAGE_PIN H9 IOSTANDARD LVDS } [ get_ports db_tx_data0_P ]
set_property -dict { PACKAGE_PIN J4 IOSTANDARD LVDS } [ get_ports db_tx_data1_N ]
set_property -dict { PACKAGE_PIN J5 IOSTANDARD LVDS } [ get_ports db_tx_data1_P ]
set_property -dict { PACKAGE_PIN H6 IOSTANDARD LVDS } [ get_ports db_tx_data10_N ]
set_property -dict { PACKAGE_PIN J6 IOSTANDARD LVDS } [ get_ports db_tx_data10_P ]
set_property -dict { PACKAGE_PIN L8 IOSTANDARD LVDS } [ get_ports db_tx_data2_N ]
set_property -dict { PACKAGE_PIN M8 IOSTANDARD LVDS } [ get_ports db_tx_data2_P ]
set_property -dict { PACKAGE_PIN J9 IOSTANDARD LVDS } [ get_ports db_tx_data3_N ]
set_property -dict { PACKAGE_PIN K9 IOSTANDARD LVDS } [ get_ports db_tx_data3_P ]
set_property -dict { PACKAGE_PIN N8 IOSTANDARD LVDS } [ get_ports db_tx_data4_N ]
set_property -dict { PACKAGE_PIN N9 IOSTANDARD LVDS } [ get_ports db_tx_data4_P ]
set_property -dict { PACKAGE_PIN H7 IOSTANDARD LVDS } [ get_ports db_tx_data5_N ]
set_property -dict { PACKAGE_PIN J7 IOSTANDARD LVDS } [ get_ports db_tx_data5_P ]
set_property -dict { PACKAGE_PIN K7 IOSTANDARD LVDS } [ get_ports db_tx_data6_N ]
set_property -dict { PACKAGE_PIN K8 IOSTANDARD LVDS } [ get_ports db_tx_data6_P ]
set_property -dict { PACKAGE_PIN P6 IOSTANDARD LVDS } [ get_ports db_tx_data7_N ]
set_property -dict { PACKAGE_PIN P7 IOSTANDARD LVDS } [ get_ports db_tx_data7_P ]
set_property -dict { PACKAGE_PIN N6 IOSTANDARD LVDS } [ get_ports db_tx_data8_N ]
set_property -dict { PACKAGE_PIN N7 IOSTANDARD LVDS } [ get_ports db_tx_data8_P ]
set_property -dict { PACKAGE_PIN H3 IOSTANDARD LVDS } [ get_ports db_tx_data9_N ]
set_property -dict { PACKAGE_PIN H4 IOSTANDARD LVDS } [ get_ports db_tx_data9_P ]
set_property -dict { PACKAGE_PIN L5 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports fdsp_clk_in_N ]
set_property -dict { PACKAGE_PIN M6 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports fdsp_clk_in_P ]
set_property -dict { PACKAGE_PIN L7 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports pl_clk0_P ]
set_property -dict { PACKAGE_PIN L6 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100 } [ get_ports pl_clk0_N ]
set_property -dict { PACKAGE_PIN E7 IOSTANDARD LVCMOS18 PULLTYPE PULLUP } [ get_ports dac_irq1_b ]
set_property -dict { PACKAGE_PIN B9 IOSTANDARD LVCMOS18 PULLTYPE PULLUP } [ get_ports dac_irq2_b ]
set_property -dict { PACKAGE_PIN C7 IOSTANDARD LVCMOS18 } [ get_ports dac_reset_b ]
set_property -dict { PACKAGE_PIN D9 IOSTANDARD LVCMOS18 } [ get_ports dac_spi_clk ]
set_property -dict { PACKAGE_PIN E9 IOSTANDARD LVCMOS18 } [ get_ports dac_spi_cs_b ]
set_property -dict { PACKAGE_PIN E8 IOSTANDARD LVCMOS18 } [ get_ports dac_spi_dio ]
set_property -dict { PACKAGE_PIN F6 IOSTANDARD LVCMOS18 } [ get_ports dac_txen ]
set_property -dict { PACKAGE_PIN B8 IOSTANDARD LVDS } [ get_ports dac_d0_N ]
set_property -dict { PACKAGE_PIN C8 IOSTANDARD LVDS } [ get_ports dac_d0_P ]
set_property -dict { PACKAGE_PIN A6 IOSTANDARD LVDS } [ get_ports dac_d1_N ]
set_property -dict { PACKAGE_PIN A7 IOSTANDARD LVDS } [ get_ports dac_d1_P ]
set_property -dict { PACKAGE_PIN A8 IOSTANDARD LVDS } [ get_ports dac_d2_N ]
set_property -dict { PACKAGE_PIN A9 IOSTANDARD LVDS } [ get_ports dac_d2_P ]
set_property -dict { PACKAGE_PIN D5 IOSTANDARD LVDS } [ get_ports dac_d3_N ]
set_property -dict { PACKAGE_PIN E5 IOSTANDARD LVDS } [ get_ports dac_d3_P ]
set_property -dict { PACKAGE_PIN E3 IOSTANDARD LVDS } [ get_ports dac_d4_N ]
set_property -dict { PACKAGE_PIN E4 IOSTANDARD LVDS } [ get_ports dac_d4_P ]
set_property -dict { PACKAGE_PIN F3 IOSTANDARD LVDS } [ get_ports dac_d5_N ]
set_property -dict { PACKAGE_PIN G3 IOSTANDARD LVDS } [ get_ports dac_d5_P ]
set_property -dict { PACKAGE_PIN B6 IOSTANDARD LVDS } [ get_ports dac_d6_N ]
set_property -dict { PACKAGE_PIN C6 IOSTANDARD LVDS } [ get_ports dac_d6_P ]
set_property -dict { PACKAGE_PIN A5 IOSTANDARD LVDS } [ get_ports dac_d7_N ]
set_property -dict { PACKAGE_PIN B5 IOSTANDARD LVDS } [ get_ports dac_d7_P ]
set_property -dict { PACKAGE_PIN C4 IOSTANDARD LVDS } [ get_ports dac_d8_N ]
set_property -dict { PACKAGE_PIN D4 IOSTANDARD LVDS } [ get_ports dac_d8_P ]
set_property -dict { PACKAGE_PIN A4 IOSTANDARD LVDS } [ get_ports dac_d9_N ]
set_property -dict { PACKAGE_PIN B4 IOSTANDARD LVDS } [ get_ports dac_d9_P ]
set_property -dict { PACKAGE_PIN A3 IOSTANDARD LVDS } [ get_ports dac_d10_N ]
set_property -dict { PACKAGE_PIN B3 IOSTANDARD LVDS } [ get_ports dac_d10_P ]
set_property -dict { PACKAGE_PIN A1 IOSTANDARD LVDS } [ get_ports dac_d11_N ]
set_property -dict { PACKAGE_PIN A2 IOSTANDARD LVDS } [ get_ports dac_d11_P ]
set_property -dict { PACKAGE_PIN B1 IOSTANDARD LVDS } [ get_ports dac_d12_N ]
set_property -dict { PACKAGE_PIN C1 IOSTANDARD LVDS } [ get_ports dac_d12_P ]
set_property -dict { PACKAGE_PIN D1 IOSTANDARD LVDS } [ get_ports dac_d13_N ]
set_property -dict { PACKAGE_PIN E1 IOSTANDARD LVDS } [ get_ports dac_d13_P ]
set_property -dict { PACKAGE_PIN F1 IOSTANDARD LVDS } [ get_ports dac_d14_N ]
set_property -dict { PACKAGE_PIN G1 IOSTANDARD LVDS } [ get_ports dac_d14_P ]
set_property -dict { PACKAGE_PIN C2 IOSTANDARD LVDS } [ get_ports dac_d15_N ]
set_property -dict { PACKAGE_PIN C3 IOSTANDARD LVDS } [ get_ports dac_d15_P ]
set_property -dict { PACKAGE_PIN D6 IOSTANDARD LVDS } [ get_ports dac_dci_N ]
set_property -dict { PACKAGE_PIN D7 IOSTANDARD LVDS } [ get_ports dac_dci_P ]
set_property -dict { PACKAGE_PIN E2 IOSTANDARD LVDS } [ get_ports dac_frm_N ]
set_property -dict { PACKAGE_PIN F2 IOSTANDARD LVDS } [ get_ports dac_frm_P ]

create_clock -add -name pl_clk0_p -period 3.2 -waveform { 0 1.6 } [ get_ports { pl_clk0_P } ]
create_clock -add -name pl_clk0_n -period 3.2 -waveform { 0 1.6 } [ get_ports { pl_clk0_N } ]
create_clock -add -name pl_clk1 -period 3 -waveform { 0 1.5 } [ get_ports { pl_clk1 } ]
create_clock -add -name pl_clk2 -period 3 -waveform { 0 1.5 } [ get_ports { pl_clk2 } ]
create_clock -add -name fdsp_clk_p -period 4 -waveform { 0 2 } [ get_ports { fdsp_clk_in_P } ]
create_clock -add -name fdsp_clk_n -period 4 -waveform { 0 2 } [ get_ports { fdsp_clk_in_N } ]
create_clock -add -name synce_clk -period 8 -waveform { 0 4 } [ get_ports { synce_clk_125mhz } ]
create_clock -add -name fdsp_clk_p -period 4 -waveform { 0 2 } [ get_ports { adc_dco_P } ]
create_clock -add -name fdsp_clk_n -period 4 -waveform { 0 2 } [ get_ports { adc_dco_N } ]
create_clock -add -name fdsp_clk_p -period 2 -waveform { 0 1 } [ get_ports { dac_dci_P } ]
create_clock -add -name fdsp_clk_n -period 2 -waveform { 0 1 } [ get_ports { dac_dci_N } ]
